### PR TITLE
DatePicker: add some waits to showPanel and hidePanel

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by tandraschko** [comment]
Why do we need this? I thought wait for Animation should fix it?

**Comment by melloware** [comment]
This particular issue doesn't appear to be animation related that I can tell.

**Comment by melloware** [comment]
I think I just realized why.  the new themes like Saga have CSS transitions on all the DatePicker popup elements we are trying to click on.

See:
image

These CSS animations cause StaleElement etc when we say find the link and "click" on it.  When you go to click or hover I think the CSS animations are changing the states of the Links in the Popup or the Popup itself.

**Comment by christophs78** [comment]
Not sure it´s this caused by CSS transitions on hover. They probably were introduced before the jQuery to CSS-animations refactoring last week.

We had some issue with panel.isDisplayed() showing the wrong state even after disabling animations.
image
This caused showPanel not to show the panel.

I´m not happy with adding some wait into showPanel/hidePanel. But at least out integrations tests work for now. We should come back to this when we have more time to investigate this into detail. But for now i´m out of time and energy. We played around with this already for a few hours. And still way to much COVID19 related work on my day-job.

**Comment by melloware** [comment]
I am trying some thing now.

**Comment by melloware** [comment]
OK I was able to remove the `wait`s by using this commit:
https://github.com/primefaces-extensions/primefaces-selenium/commit/3cf8d309297702330e91fe6c3ca21db5b0537efb

Still debugging one more issue.

**Comment by melloware** [comment]
OK the tests still flicker even with `transition` animations turned off. For now I put back the wait but I concur with @christophs78 there is something asynchronous going on with `showPanel` that I am just not seeing because the panel says its displayed=true when its not supposed to be.  But waiting 100ms the `panel.isDiplayed` evaluates correctly.

**Comment by christophs78** [comment]
onDateSelect as part of 0-datepicker.js does following:
```javascript
onDateSelect: function (event, dateMeta) {
   ...
   if (!this.options.inline && this.isSingleSelection() && (!this.options.showTime || this.options.hideOnDateTimeSelect)) {
      ...
      setTimeout(function () {
         $this.hideOverlay();
      }, 100);
      ..
}
```

That´s probably our root issue. So we need to wait.

**Comment by melloware** [comment]
AHhh I was looking in ShowOverlay not thinking HideOverlay.  Yep there is nothing we can do we have to use these waits.

**Pull request merged**
