### PR TITLE
Implement #10: TabView: Selenium Wrapper

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by tandraschko** [comment]
basically +1
but maybe we can add a "Tab" component which has a index, header, styles 
so we dont have #getActiveTabHeader, #getActiveTabIndex and so on - just one single "Tab getActiveTab"

**Comment by christophs78** [comment]
Ok, i´ll look at this. (adding "Tab"-component)

Some further thoughts:
- Shared code between AccordionPanel and TabView
- dynamic mode (tab-content is loaded on demand); may have further implications

**Comment by melloware** [comment]
Don't forget to update the README.MD with this new component too.

**Comment by tandraschko** [comment]
-1 melloware
We should add a Tab component

**Comment by melloware** [comment]
Whether we refactor to tab or not I think each component should line up 1 to 1 with a PF component or else end users will be confused. Don't you ?

its like saying use InputText for a Spinner component.  While it will work its not quite what a user was looking for?

**Comment by melloware** [comment]
Oh I think I see what you are saying the TabView component should return Tab items etc.

**Comment by christophs78** [comment]
From my side i plan to contribute some more time. Just have to align this with my day job and other things that need to be done.

**Comment by melloware** [comment]
@christophs78 No problem.  It looks like how Thomas did Messages is a similar example of how we can extract Tabs using a model object.

**Comment by tandraschko** [comment]
Exactly and Tab should be child-component of TabView Like in PF

**Pull request merged**
