### PR TITLE
disable CSS-Animations

### PR DESCRIPTION
**Pull request by christophs78**
We may add some switch to toggle css-animations on/off.
For most integration-tests IMO css-animations are not necessary.

### CODE REVIEW

**Comment by melloware** [comment]
OK I like where you are going with this.  Just need to add the new config to ConfigProvider for globally turning it off with a property like there is with jquery animations...

**Comment by christophs78** [comment]
further discussion: https://github.com/primefaces-extensions/primefaces-integration-tests/issues/120

**Comment by melloware** [comment]
I just added this too I thought it would be good to have in there: https://github.com/primefaces-extensions/primefaces-selenium/commit/bad740a19605214bfed85386fcddd7cdbd284c26

**Comment by christophs78** [comment]
> I just added this too I thought it would be good to have in there: [bad740a](https://github.com/primefaces-extensions/primefaces-selenium/commit/bad740a19605214bfed85386fcddd7cdbd284c26)

Yep. At least good as a first step. Personally i´m not totally happy with polling BoundingClientRect. Personally i would prefer some simpler solution if we can find one.

**Comment by melloware** [comment]
me too

**Comment by melloware** [comment]
I reverted it.  Didn't make anything any better.  I think the real problem is the asynchronous.  An easy fix might be is we set the ` `jQuery.active = 1;` and ` jQuery.active = 0;` in the core new PF animation code.  Think that would work?  Basically just signalling that an animation is happening?

**Comment by melloware** [comment]
I implemented this but used a more aggressive CSS.
```css
*, *:before, *:after {
    -webkit-transition: none !important;
    -moz-transition: none !important;
    -ms-transition: none !important;
    -o-transition: none !important;        
    transition: none !important;
}
```

**Pull request closed without merging**
